#!/usr/bin/env bash

set -e

snippets_dir_path=".snippets"

rm -rf "${snippets_dir_path}"
mkdir "${snippets_dir_path}"

python scripts/collect_snippets.py

ruff format --check "${snippets_dir_path}"
ruff check --ignore-noqa --select E,F,I,B "${snippets_dir_path}"
mypy "${snippets_dir_path}"

rm -rf "${snippets_dir_path}"
